### ISSUE TITLE
bottom overflow when typing in password

### ISSUE THREAD

**Issue by NikomitK** [Kreck-Projekt/DoorOpenerApp#1]
"bottom overflowed 36 pixels" or something like that when the keyboard is visible

**Comment by jxstxn1** [comment]
Thanks for your complain, can you please provide the Screen where the issue show up and If possible screenshots?

**Comment by NikomitK** [comment]
![image](https://user-images.githubusercontent.com/68833349/105950233-51cd2500-606e-11eb-8a67-ac762a2d652f.jpeg)

It happens everytime I have to type in my password.

**Comment by jxstxn1** [comment]
We updated the repository, try it again after updating the app
